playerSave = open("players.sav","w")
playerSave.write("{}")
playerSave.close()
itemSave = open("items.sav","w")
itemSave.write("{}")
itemSave.close()
roomSave = open("rooms.sav","w")
roomSave.write("{}")
roomSave.close()
